# Generated by Django 2.0.1 on 2018-02-06 12:25

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=False, to='Book.Area')),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='书名')),
                ('pub_date', models.DateField(null=True, verbose_name='出版日期')),
                ('readcount', models.IntegerField(default=0, verbose_name='阅读数')),
                ('commentcount', models.IntegerField(default=0, verbose_name='评论数')),
                ('isDelete', models.BooleanField(default=False, verbose_name='展示')),
            ],
            options={
                'db_table': 'book',
            },
            managers=[
                ('books', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CostomizedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='Book/', verbose_name='图片路径')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=False, to='Book.Book')),
            ],
            options={
                'db_table': 'role',
            },
            managers=[
                ('roles', django.db.models.manager.Manager()),
            ],
        ),
    ]
